### ISSUE TITLE
LIBEAY32 - Crash since the update in 5.2.0

### ISSUE THREAD

**Issue by abrochet** [MapWindow/MapWinGIS#195] opened 2020-06-02 08:12 UTC
Hello,

My application crashes randomly (often when starting). According to the event viewer there is a problem with: LIBEAY32.dll

![image](https://user-images.githubusercontent.com/24960001/83495705-5b3ec700-a4b8-11ea-9b02-aca13cd1f10b.png)

Do you have an idea about the source of this problem please ? I can't find more information...
Thanks,
Anthony,

**Comment by pmeems** [comment] 2020-06-02 08:28
You didn't have this problem with v5.1 of MapWinGIS?

libeay32.dll contains encryption functions that allow for coded communications over networks.
It is part of the GDAL binaries. 
We don't use it directly in MapWinGIS. 

Looking at the timestamp it doesn't seem to be changed since September 2017.

Do you have other versions of MapWinGIS installed on your computer?

**Comment by abrochet** [comment] 2020-06-02 08:49
No, it's the first time this has happened. I only have version 5.2.0 on my computer.

**Comment by pmeems** [comment] 2020-06-02 09:59
Do you have `LIBEAY32.dll` in other locations on your computer? Perhaps in `Windows\System`.
And can you run dependency walker on the dll. Perhaps it needs an additional file?

**Comment by abrochet** [comment] 2020-06-02 12:48
It has appeared twenty times on different programs.
I managed to have the DLL which is problematic on the internet, and I passed my application in x64. For now I don't have any more crashes but as it happens randomly, I don't want to declare victory too quickly. I will come back to you at the end of the week to let you know if everything is good because I would like other users to test before confirming.

**Comment by abrochet** [comment] 2020-06-16 14:02
Hello,

Sorry I have forgotten to give you my feedback. I still have random crashes on several PCs, however the version 5.1.1 works perfectly.

**Comment by pmeems** [comment] 2020-06-16 15:11
Yesterday I published a hotfix (v5.2.1) would you mind trying that version and letting us know if your problem persists.

Thanks.

**Comment by abrochet** [comment] 2020-06-22 15:20
Hello, I still have the same mistake but less frequently.

**Comment by pmeems** [comment] 2020-07-10 08:29
It seems GisInternals has updated his binaries and now includes the libssl-1_1 and libcrypto-1_1 dlls.
I updated our build process and created new installers. For now only available at my Google Drive:
https://drive.google.com/drive/folders/0B8UeIGgvyx2VQXRDVndvTUVlUFE?usp=sharing 

Since I can't reproduce the mentioned error, can you (@abrochet) test this version and let us know?

**Comment by abrochet** [comment] 2020-07-10 13:28
Hello,

Thanks, I'll take care of it next week.

**Comment by abrochet** [comment] 2020-07-17 15:23
it works perfectly thank you :)
Is it fixed from which version?

Thanks,

**Comment by pmeems** [comment] 2020-07-24 06:59
It has been fixed in the fourth release candidate available at https://github.com/MapWindow/MapWinGIS/releases/tag/v5.2.3

**Closed as completed by pmeems** 2020-07-24 06:59 UTC
