### ISSUE TITLE
MapWinGis mbtiles

### ISSUE THREAD

**Issue by kinsung** [MapWindow/MapWinGIS#128] opened 2018-10-27 00:31 UTC
Can MapWinGIs use .mbtiles Maps as offline maps? How to add a mbtiles layer to MapWinGIS?

**Comment by jerryfaust** [comment] 2018-12-20 23:22
@kinsung , see comment added to #133

**Comment by JaqucesT** [comment] 2018-12-23 10:58
Looking at the provided methods i would suggest a strong YES. 
You have the possibility to define your own tileprovider (<mapobject>.tileprovider) and switch DiskCaching on (<mapobject>.DiskCacheFilename / <mapobject>.DoCaching), - this will create a .mbtiles-File. When you load this map again without a connection to your tileprovider the cache file is read instead. There are also methods to prefetch all the tiles needed.
Unfortunately my ms-access sample application does run fine only for some minutes, and the more threads i allow to fetch tiles (<GlobalSettings>.TilesThreadPoolSize), the faster ms access crashes.
So the method to load tiles offline from an mbtiles-File is already present and working, but with my limited knowledge i would say: not stable.
That's very sad, - i would really need this feature to run stable, - currently my only show-stopper for not implenting this component into my projects.

**Comment by jerryfaust** [comment] 2018-12-23 19:08
Thanks for the feedback, @JaqucesT 

Regarding the issues with ms-access, are you sure the problems are not with access as opposed to the caching algorithm?  ms-access is not thread-safe, and in my experience, to get consistent behavior (from an external application) I have had to funnel all calls through a queue in order to force them through ms-access single-file.  This may be related to the issues you are having.

If you don't mind attaching a database and some sample code, I could try to look it over to see where it is breaking down.  I believe the tile caching is being used extensively, and if indeed there are any issues, we would like to get them resolved.

Regards.
Jerry.

**Comment by JaqucesT** [comment] 2018-12-27 17:33
Hi Jerry,

would be very happy, to get this resolved.
Attached you find an MS-Access database that tries to prefetch tiles into a local directory and into a local sql-litedb.
When you open the database you simply need to open the one and only form in this db, that will create a directory "tiles" and a file "tilecache.sdb" in the db-directory and immediately start to prefetch the tiles of a given Map-Boundary from zoomlevel 1 to 19.
If you look at the immediate window, it will tell you, what it does, and reports all the errors that are thrown from the callback-object. A log-file is also created in the same directory.
Somewhere around Zoomlevel 11 it will just crash.

If you have questions, i'll try to answer asap.

Thanks and
Cheers

Stefan

[MapWinGis_TilesTest.zip](https://github.com/MapWindow/MapWinGIS/files/2712950/MapWinGis_TilesTest.zip)

**Comment by JaqucesT** [comment] 2019-01-03 11:27
Hi Jerry,

and Happy New Year!

I just want to follow up on this issue, - any news about this?
Anything i can do to help?

Thanks and
Cheers

Stefan

**Comment by jerryfaust** [comment] 2019-01-04 06:17
I'm sorry for the delay, @JaqucesT , I had not yet gotten to it.

But I did just open it up and did a little debugging.  It took a few tries, but based on my concern that Access has issues with threading, I tried setting the TilesThreadPoolSize = 1, and commented out all of the DoEvents and WaitASecond calls, since these allow asynchronous activities to take place, and it ran to completion, displaying the resulting tiles.

I think the next step would be to move this code into a simple vb.net program, and see how it behaves there.  Once it is in vb.net, we could explore multithreaded activities just to verify that they work properly.

Here's the modified section of Form_Load (note that the VB script comment character (single quote) messes up the inserted code, although in this case, it helps emphasize the code that I've commented):

`
    myGlobalSettings.TilesThreadPoolSize = 1
    'myGlobalSettings.TilesThreadPoolSize = 16
    myGlobalSettings.AutoChooseRenderingHintForLabels = True
    myGlobalSettings.ShapefileFastMode = True
    
    If (clsStopFunction Is Nothing) Then Set clsStopFunction = New StopInterface
    
    If (myCallBack Is Nothing) Then
        Set myCallBack = New clsCallback
        myGlobalSettings.ApplicationCallback = myCallBack
    End If

    Set gpTemp = New MapWinGIS.GeoProjection
    Call gpTemp.ImportFromProj4("+proj=merc +a=6378137 +b=6378137 +lat_ts=0.0 +lon_0=0.0 +x_0=0.0 +y_0=0 +k=1.0 +units=m +nadgrids=@null +wktext  +no_defs")
    
    Set Me.MapMain.GeoProjection = gpTemp
    
    Set extProvider = New MapWinGIS.Extents
    extProvider.SetBounds 8.53131901143695, 49.6634333399756, 0, 8.7376422643129, 49.7222568328034, 0
    
    Set extMap = New MapWinGIS.Extents
    extMap.SetBounds 466183.63735818, 5501294.54970538, 0, 481087.801982757, 5507831.1133398, 0
    
    Me.MapMain.TileProvider = MapWinGIS.tkTileProvider.OpenStreetMap
    Me.MapMain.Tiles.MinScaleToCache = 1
    Me.MapMain.Tiles.MaxScaleToCache = 19
    Me.MapMain.Tiles.DiskCacheFilename = Com_GetFileNamePart(CurrentDb.Name, True) + "TileCache.sdb"
    Me.MapMain.Tiles.DoCaching(tkCacheType.RAM) = False
    Me.MapMain.Tiles.DoCaching(tkCacheType.Disk) = True
    
    Set Me.MapMain.Extents = extMap
    Me.MapMain.CursorMode = tkCursorMode.cmPan
    Me.MapMain.SendSelectBoxFinal = True
    Me.MapMain.SendMouseDown = True
    Me.MapMain.SendMouseUp = True
    Me.MapMain.InertiaOnPanning = tkCustomState.csAuto
    Me.MapMain.Identifier.IdentifierMode = tkIdentifierMode.imSingleLayer
    Me.MapMain.Identifier.HotTracking = True
    Me.MapMain.Measuring.UndoButton = tkUndoShortcut.usRightMouseButton
 
    'DoEvents: DoEvents: DoEvents
    Me.MapMain.Tiles.DelayRequestTimeout = 60
    'Me.MapMain.Tiles.SleepBeforeRequestTimeout = 0
        
    If (Not (myGlobalSettings Is Nothing)) Then _
        Call myGlobalSettings.StartLogTileRequests(Com_GetFileNamePart(CurrentDb.Name, True) + "log.txt", True)
    
    Call Me.MapMain.LockWindow(tkLockMode.lmLock)
    clsStopFunction.Starten
    
    strTemp = Com_GetFileNamePart(CurrentDb.Name, True) + "tiles\"
    
    If Len(Dir(strTemp, vbDirectory)) = 0 Then
        MkDir strTemp
    End If
    
    For intZoomRunner = 1 To 19
    
        Debug.Print "Lade Zoom-Level: " + CStr(intZoomRunner)
    
        bolTilesLoaded = False
        
        lngResult = Me.MapMain.Tiles.PrefetchToFolder(extProvider, intZoomRunner, Me.MapMain.Tiles.ProviderId, strTemp, ".png", clsStopFunction)
        
'        DoEvents
'        WaitASecond 1
'        DoEvents
'        WaitASecond 1
'        DoEvents
'        WaitASecond 1
'        DoEvents
        
        Debug.Print "-------------------------------------"
        Debug.Print "Zoom: " + CStr(intZoomRunner) + ", Prefetch-Result: " + CStr(lngResult)
        Debug.Print "-------------------------------------"
'        DoEvents: DoEvents: DoEvents
        
    Next
    
    Call Me.MapMain.LockWindow(tkLockMode.lmUnlock)
    
    Me.MapMain.Tiles.ClearCache tkCacheType.RAM
    Me.MapMain.Tiles.DoCaching(tkCacheType.RAM) = True
    Me.MapMain.Tiles.UseCache(tkCacheType.Disk) = True

Function_End:
    On Error Resume Next
    
    Call Me.MapMain.LockWindow(tkLockMode.lmUnlock)
   
    If (Not (clsStopFunction Is Nothing)) Then clsStopFunction.Stoppen
'    DoEvents: DoEvents: DoEvents
    
    If (Not (myGlobalSettings Is Nothing)) Then _
        Call myGlobalSettings.StopLogTileRequests
    
    If Len(strErrorMessage) > 0 Then _
        Debug.Print strErrorMessage
    
Exit Sub

`

**Comment by JaqucesT** [comment] 2019-01-04 11:15
Hi Jerry,

many thanks for looking into that issue.

Unfortunately this approach doesn't seem to solve the issue. In my ms-access-application i deleted all occurences of "DoEvents", set the TilesThreadPoolSize to 1, but after zooming in and out for a while Access crashed as before.
This application doesn't do a prefetch at all, just normal moving around in the mapwindow with pan and zoom tools.

I'm currently trying to do the same as you suggested and try to implement disk caching with a local SQL-LiteDB-File in the demo app, that comes with the MapWinGIS-SourceCode, but didn't succeed so far.

Adding my own tileprovider works, but the CacheFile never appears in the filesystem:

          App.Map.Tiles.Providers.Add(1030, "LocalOSM", "http://192.168.178.172/osm/{zoom}/{x}/{y}.png", tkTileProjection.SphericalMercator, 1, 19);
          App.Map.TileProvider = tkTileProvider.ProviderCustom;
          App.Map.Tiles.ProviderId = 1030;
            App.Map.Tiles.DiskCacheFilename = "C:/Temp/tileCache.sdb";
            App.Map.Tiles.DoCaching[tkCacheType.RAM] = true;
            App.Map.Tiles.DoCaching[tkCacheType.Disk] = true;
            App.Map.Tiles.UseCache[tkCacheType.Disk] = true;
            App.Map.Tiles.MinScaleToCache = 1;
            App.Map.Tiles.MaxScaleToCache = 19;

Compile & run don't throw any error messages, simply no file is generated.
Exactly the same work with the OCX in MS-Access, but not here, - maybe i forgot a detail.
Any hint about this?

Cheers
Stefan

**Comment by JaqucesT** [comment] 2019-01-04 11:40
Ok, the cachefile appears and gets used, when the path doesn't contain "_", so that works.

**Comment by JaqucesT** [comment] 2019-01-18 11:26
Hi,

has anyone changed the Tiles-/TileProvider-API with new release 5.0?

After installing the release the above mentioned project crashes MS-Access reproducably with only opening the formerly working form.

When loading the form I get tons of messages in the immediate window:

Callback / ErrorMessage: SQLiteCache::DoCaching: Failed to prepare statement.

without having set anything about caching, and MS-Access crashes, when i try to set my own tileprovider, - code see above.

What happened?

Stefan

**Comment by JaqucesT** [comment] 2019-01-20 11:45
Hi,

if someone still reads these posts:

I just created a new Access-DB with a single form containing only a mapcontrol (V 5.0).
a few lines in Form_Load to add a tileprovider and i get the same error messages mentioned in my previous post and access crashes reliably after some zoom operations.

attached this simple database

thanks for any help
Stefan

[Database1.zip](https://github.com/MapWindow/MapWinGIS/files/2776533/Database1.zip)

**Comment by jerryfaust** [comment] 2019-01-20 16:33
Thank you, @JaqucesT 

I will try to look at this soon.

**Comment by JaqucesT** [comment] 2019-01-22 16:07
Hi Jerry,

just downloaded the development branch and build it in VS 2017, registered it successfully with regsvr32 and created a new MS-Access-DB with a form & MapControl.

The error "SQLiteCache::DoCaching: Failed to prepare statement" as mentioned above doesn't appear, but as before, first time i try to access <MapObject>.Tiles Class, i get this error:

Library not registered.  / -2147319779

--> the error appeared also after this SQLiteCache-Error, so maybe this is the real source of the error

as i wrote: regsvr32 (used both references (system32/syswow64)) claimed SUCCESS when registering, and creating a mapcontrol in the form worked without error messages.

Thanks for any hint

Cheers
Stefan

**Comment by jerryfaust** [comment] 2019-01-22 19:09
Hello Stefan.

I have not tried this latest test yet, but I wonder if it is related to SQLite.  Are you building your own version of GDAL?  I build my own GDAL in order to debug and to get certain database drivers, and according to their documentation, the SQLite drive is not built in (see [OGR Vector Formats](https://www.gdal.org/ogr_formats.html)). This makes me wonder if SQLite is the library that is not registered.

I'm just speculating at this point, and I will try to test this on my end.  I'm currently doing a rebuild of the latest GDAL to link into the latest MapWinGIS, and I will include SQLite (among others) in my build, and see what happens.

Regards.
Jerry.

**Comment by JaqucesT** [comment] 2019-01-22 19:25
Hi Jerry,

I'm not a c/cpp Programmer, just clutching at straws here, so if my compiled ocx wouldn't work, i wouldn't wonder. But as i wrote, the first error messages i reported about V 5.0 appeared with the installed release from github.

And: this all worked on the same machine with the previous version 4.9.3 of MapWinGIS, - this is even more strange.

--> maybe you can find the time to install somewhere the current v 5.0 32-bit release build and test that Access-Db (see above), - only to verify, that you have or have not the same error.
If everything is alright on your machine, - then i know, i have a chance with fizzeling on my computer to get it running.

right now i build with the gdal-stuff i get from gisinternals.com. I don't get most of the settings in VC 2017, - right now i only succeed in generating a debug build. when trying to create a releas build, i get a linker error LNK2019 about an unresolved symbol in Utils.obj, - support libraries are build in debug & release.

Thanks for anything
and
regards

Stefan

**Comment by jerryfaust** [comment] 2019-01-22 21:30
Ok.  I'll let you know what I can find out.

**Comment by jerryfaust** [comment] 2019-01-23 01:18
Hello Stefan.

Ok.  Some progress.  MSAccess is unhappy with the Tiles property.  The 'Library not registered' error is being raised by MSAccess on that line of code - it is not even getting in to the MapWinGIS code.

If instead, I set the provider as follows, then it works:

`Me.Map0.TileProvider = tkTileProvider.OpenStreetMap`

I'm guessing there's some obscure COM thing going on, but I don't yet know what it is.  I'll keep looking.

Regards.
Jerry

**Comment by jerryfaust** [comment] 2019-01-23 06:16
Follow-up:

Here's what I think is going on.  It has to do with the rules of COM.

Although many of the Interfaces in MapWinGIS are so-called 'dual' interfaces, the DMap Interface is strictly a Dispatch interface.  The short of it is that, at least through VBA, you cannot piggy-back method calls into COM - it only knows how to get the first level return value, which in this case is the Tiles object reference.  This explains why we can make the `Map0.TileProvider` call, but cannot make the `Map0.Tiles.ProviderID` call.

So we first have to extract the Tiles reference into a variable `t`, then make the call into `t.ProviderID`, as follows:

    Dim t As MapWinGIS.Tiles
    Set t = Me.Map0.Tiles
    t.ProviderId = tkTileProvider.OpenStreetMap

This works.  (of course, in this case, we can simply make the TileProvider call since it does the same thing, but the single-level rule here will apply to all Map calls).

So now that we're past that, I went back to the issue related to MS Access crashing.  Sure enough, I was able to repeatedly zoom in and out and throw an exception.  And fortunately, I was able to hook the debugger and see where the exception was being thrown.  It was in the FireExtentsChanged event, and had something to do with it being 'expired'.  But I was only able to do it once, and couldn't repeat it, so I'll continue to review it.  I have a recollection that this has been reported before.

Regards.
Jerry.

**Comment by jerryfaust** [comment] 2019-01-23 06:41
I found the related issue, #59 (Crash while zoom with mouse wheel), and interestingly, it is also within MS Access.  So I think that's the common thread here - I don't believe we have seen this anywhere else.  So I'll revisit this soon and see if I can pin it down.

**Comment by JaqucesT** [comment] 2019-01-23 09:27
Good morning Jerry,

Thank you very much for investing your time!

You're right, to create an object variable first and let it point to the mapproperty-class works, and that's also valid for all "second-level" property-classes.
That was shurely different for version 4.9.3 - the same code didn't throw errors.
But good news, now the application runs as before, - great.

I just read the post that you linked to, and even that it doesn't solve a thing, it's good to know i'm not the only one with a crashing ms access.

If there's anything i can do to help you find the source of the exception, let me know.
Would be really great to get that issue solved.

Thanks again and
best regards

Stefan

**Comment by IndustryRU** [comment] 2019-01-23 09:48
Good day! I noticed that if you disable caching in the MS Access settings, the stability of the map scaling is significantly improved. Maybe there's a connection. 

Options -> Current database -> caching web service and SharePoint tables

My best regards
Alexei

**Comment by JaqucesT** [comment] 2019-01-23 13:59
Hi,

maybe it's not only the mousewheel-zoom that causes the crash.

I just tried to setup a routine to prefetch all tiles in a given region and Access crashes everytime (!) when issuing this command:

dim tlsTemp as MapWinGIS.Tiles

set tlsTemp = Me.MapMain.Tiles

debug.print tlsTemp.Prefetch(49.6247, 49.7980, 8.4732, 8.7745, 18, tlsTemp.ProviderId, clsStopFunction)

- it doesn't matter, if a local WMST-Service is used or OpenStreetMap-TileProvider

I monitored the unencrypted network-traffic to my local WMST-server and after issuing this command valid tile requests are issued to the server and valid png-files are comming back.
And interrestingly enough, - when i set 

myGlobalSettings.TilesThreadPoolSize = 16

Wireshark shows exactly 16 successful tile requests/png-responses before access crashes.
setting it to 32, - crashes Access when trying to open the map.
setting it to 8 shows exactly 8 successful tile requests/png-responses before access crashes.

![threadpoolsize_8](https://user-images.githubusercontent.com/34768911/51607225-67a22f80-1f14-11e9-9667-c4d7790c432b.png)

...ok, setting TilesThreadPoolSize=1 leads to a crashing access after one successful request.
mh.

the local sqlite-cache file doesn't change at all.
When changing the mapview with the map tools the sqlite-cachefile gets bigger and bigger.

It doesn't make a difference if only disk caching or only RAM caching is used, in both cases access crashes after a while, when zooming in and out.

@Alexei
Caching options were never enabled in my database.

will keep investigating

kind regards
Stefan

**Comment by pmeems** [comment] 2019-03-22 09:10
Just to get this back on the radar. 
@JaqucesT Do you still have these problems with MS-Access and the latest (stable or dev) version of MapWinGIS?

**Comment by IndustryRU** [comment] 2019-03-25 05:03
Good day!
Support question @pmeems.
@JaqucesT did you manage to fix the crash?

My best regards
Alexei

**Comment by IndustryRU** [comment] 2019-03-27 06:58
We have update the version of MapWinGIS to v5.0.1.
Problems with MS-Access practically do not occur!
Perfect!

Thank very much!
Regards,
Alexei

**Comment by pmeems** [comment] 2019-03-28 13:58
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)

**Closed as completed by pmeems** 2019-03-28 13:58 UTC
