### ISSUE TITLE
System.AccessViolationException after EditAddShape

### ISSUE THREAD

**Issue by mtrfnv1** [MapWindow/MapWinGIS#166] opened 2019-06-17 10:48 UTC
I need to programmatically add a point to the map, and then build a polygon, starting from this point. That is, to build a polygon began from the second point

I tried to execute the code below:

```
Point point = new Point {x = xEnd, y = yEnd};

Shape shape = new Shape();
shape.Create(ShpfileType.SHP_POLYGON);
shape.InsertPoint(point, 0);

Shapefile shapefile = new Shapefile();
shapefile.CreateNewWithShapeID("", ShpfileType.SHP_POLYGON);
shapefile.EditAddShape(shape); // !!!
shapefile.InteractiveEditing = true;

axMap.AddLayer(shapefile, true);

axMap.ShapeEditor.StartEdit(1, 0);
```

I see my point on map, but after this instantly I get System.AccessViolationException error. What am I doing wrong?

**UPD:** When I select a point or line as a shape type, this error does not occur and everything works as it should

**Comment by mathijs-dumon** [comment] 2019-06-19 08:03
Do you mean you want to provide the user with the starting point and let him/her finish it?
If so - I had a similar requirement and with the latest development build of mapwingis I can do this:

   axMap.MapCursor = MapCursor.AddShape;
   axMap.StartNewBoundShape(layerHandle);
   axMap.ShapeEditor.AddPoint(point);

However this is probably not available in the released build yet. 

also you should use the returned index from shapefile.EditAddShape(shape); to check if the add was a success, this function will return -1 if it failed (which could be the case here)

The access violation might be triggered because of something else in the code. Can you provide a minimal example to reproduce this?

**Comment by mathijs-dumon** [comment] 2019-06-19 08:06
Also created a ticket for this in our Jira: https://mapwindow.atlassian.net/browse/MWGIS-174

**Comment by pmeems** [comment] 2019-06-21 15:15
Since a JIRA ticket is made and the discussion is moved to the discussion forum: https://mapwindow.discourse.group/t/system-accessviolationexception-after-editaddshape/196/3
I'm closing this issue.

**Closed as completed by pmeems** 2019-06-21 15:15 UTC
Labels: bug, help wanted
