### ISSUE TITLE
bug googlemap in v5.0

### ISSUE THREAD

**Issue by zontick** [MapWindow/MapWinGIS#140] opened 2019-01-21 12:07 UTC
Googlemap stop work in v5.0.

**Comment by pmeems** [comment] 2019-01-21 12:19
No, it didn't. Due to the Google restrictions, it is not allowed for us to use the Google API anymore.
Support has been removed several versions before.

**Comment by HollidayHT** [comment] 2019-02-22 13:46
I understand the google satellite images/hybred tiles are restricted but it appears that 5.0 did break the google terrain and google streets tiles. Is that by design? I don't believe the same restrictions apply to these options.

**Comment by pmeems** [comment] 2019-02-22 14:19
Doing a quick search and I couldn't find anything clear if it is or isn't allowed.
I did find this post: https://stackoverflow.com/questions/44520345/how-do-i-enable-google-maps-tile-api
The relevant part: 
`I contacted Google Maps Sales Team. The response was negative. Tiles API is deprecated and cannot be licensed anymore. – Vyacheslav Lanovets Oct 16 '18 at 22:29`

But if you find a working URL you can add it as a custom provider.
If it is really working we could consider adding it back to MapWinGIS as one of the predefined tiles providers.

**Comment by HollidayHT** [comment] 2019-02-22 15:56
The terrain and streets tiles were working before 5.0. We license googles satellite images separately but really need the terrain layer for land use. I did look through the code to see what had changed but haven't been able to get them working yet.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by pmeems** [comment] 2019-03-28 13:21
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)

**Closed as completed by pmeems** 2019-03-28 13:21 UTC
