### ISSUE TITLE
problem of  axMap.ClearDrawing(int drawHandle)

### ISSUE THREAD

**Issue by liulunheng** [MapWindow/MapWinGIS#28] opened 2017-05-26 09:07 UTC
in documention given by http://www.mapwindow.org/documentation/mapwingis4.9/class_ax_map.html, the correct action of method axMap.CleartDrawing(int drawHandle) is clear drawings on the layer with the given handle and the drawing layer keeps. However, actually when the method is invoked, the drawing layer with the drawHandle will be deleted. I couldn't go on drawing on the same layer. In some condition, I need the layer keeps all the time even i delete the drawings on the layer. How can me solve the problem? thank you

**Comment by MarkCupitt** [comment] 2017-07-03 02:58
Related to #29

**Comment by Nogginboink** [comment] 2018-09-15 05:02
I just ran into this tonight. Glad to know I'm not alone. Since this bug is nine months old with no comments from the developers, I have to assume it won't be fixed.

**Comment by pmeems** [comment] 2018-09-15 15:02
Can you show a few lines of code to reproduce this?
I will make a unit test for it and see if we can fix it.

Of course you can have a look at the C++ code and suggest a fix as well.

**Comment by Nogginboink** [comment] 2018-09-15 18:06
I looked at the code, but since I'm not familiar with the codebase, nothing jumped out at me. Here's a simple repro on a C# WinForm:

 ```
public Form1()
        {
            InitializeComponent();
            AxMap.CursorMode = tkCursorMode.cmPan;
            AxMap.InertiaOnPanning = tkCustomState.csFalse;
            AxMap.Projection = tkMapProjection.PROJECTION_GOOGLE_MERCATOR;
            AxMap.TileProvider = tkTileProvider.OpenHumanitarianMap;
            AxMap.KnownExtents = tkKnownExtents.keUSA;
        }

private void btnTest_Click(object sender, EventArgs e)
        {
            MessageBox.Show("About to create a new draw layer...");
            int newLayer = AxMap.NewDrawing(MapWinGIS.tkDrawReferenceList.dlSpatiallyReferencedList);
            MessageBox.Show("Last Error: " + AxMap.LastErrorCode.ToString());
            MessageBox.Show("New Layer: " + newLayer.ToString());
            MessageBox.Show("Going to plot a red point.");

            double lat = 32;
            double lon = -100;
            double projX = 0;
            double projY = 0;
            bool bSuccess = AxMap.DegreesToProj(lon, lat, ref projX, ref projY);

            MessageBox.Show("Result of DegreesToProj: " + bSuccess.ToString());
            MessageBox.Show("Last Error: " + AxMap.LastErrorCode.ToString());

            AxMap.DrawPointEx(newLayer, projX, projY, 5, Convert.ToUInt32(ColorTranslator.ToOle(Color.Red)));

            MessageBox.Show("Last Error: " + AxMap.LastErrorCode.ToString());

            MessageBox.Show("Going to clear that layer.");
            AxMap.ClearDrawing(newLayer);
            MessageBox.Show("Last Error: " + AxMap.LastErrorCode.ToString());

            MessageBox.Show("Going to plot a blue point.");
            AxMap.DrawPointEx(newLayer, projX, projY, 5, Convert.ToUInt32(ColorTranslator.ToOle(Color.Red)));
            MessageBox.Show("Last Error: " + AxMap.LastErrorCode.ToString()); //Shows error 1202
        }
```

**Comment by jerryfaust** [comment] 2018-09-16 02:23
Hello All.

**Perhaps in answer to the original question**, the solution is to immediately create a NewDrawing following the ClearDrawing call.  Here is a snippet of code from a sample application I have used in the past, in which I can interactively draw circles or polygons within the MouseMove event.  The drawing is initiated within the MouseDown event, and completed in the MouseUp event.  And on each MouseMove, I clear the previous drawing and draw a new drawing based on the new mouse position.  So to 're-use' the drawing layer, you would follow each ClearDrawing call with a NewDrawing call, as follows:

```
Private Sub AxMap1_MouseMoveEvent(sender As Object, e As AxMapWinGIS._DMapEvents_MouseMoveEvent) Handles AxMap1.MouseMoveEvent
        Debug.WriteLine("AxMap1_MouseMoveEvent")
        Dim util As New Utils
        '
        If _drawingCircle Then
            AxMap1.ClearDrawing(_drawHandle)
            _drawHandle = AxMap1.NewDrawing(tkDrawReferenceList.dlScreenReferencedList)
            _radius = Math.Sqrt((_mouseX - e.x) ^ 2 + (_mouseY - e.y) ^ 2)
            AxMap1.DrawCircleEx(_drawHandle, _mouseX, _mouseY, _radius, 65280, True)
        ElseIf _drawingPolygon Then
            AxMap1.ClearDrawing(_drawHandle)
            _drawHandle = AxMap1.NewDrawing(tkDrawReferenceList.dlScreenReferencedList)

            x(_numPoints) = e.x
            y(_numPoints) = e.y
            If _numPoints = 1 Then
                AxMap1.DrawLineEx(_drawHandle, x(0), y(0), x(1), y(1), 1, &HFF0000)
            Else
                x(_numPoints + 1) = x(0)
                y(_numPoints + 1) = y(0)
                AxMap1.DrawPolygonEx(_drawHandle, x, y, _numPoints + 2, &HFF0000, False)
            End If
            AxMap1.Redraw2(tkRedrawType.RedrawSkipDataLayers)
            . . . .

```

**In answer to the second question**, as to there being no error reported when drawing to an invalid drawing layer, that is really a separate issue.  I have briefly reviewed the code, and it looks as if an error should be reported (tkINVALID_DRAW_HANDLE), and in fact, @Nogginboink reports that he is getting that error.  So I'm not sure if that is actually an issue.  I will do more review.

**Comment by Nogginboink** [comment] 2018-09-16 13:12
I understand that a new layer can be created after clearing a layer, and that is in fact what I am planning to do. However... if that's the 'correct' solution, then why have a Clear method at all on the layer? In this case, isn't Clear the same as Remove? If so, the Clear method should be removed from the API in favor or removing the layer.

**Comment by jerryfaust** [comment] 2018-09-17 02:25
Hello @Nogginboink 

I see what you're saying.  The issue is with the meaning of Clear.  Admittedly, when you Clear a Shape, the points and parts are cleared, but the Shape remains intact.  It's hard to say what the creators of the API had in mind, but at this point, it is what it is.  The drawing layers are more transient that the standard layers, intended for fast drawing of temporary elements on top of the map.  So they aren't 'added' or 'removed' like other layers.  Perhaps the original thinking was that NewDrawing and ClearDrawing was analogous to AddLayer and RemoveLayer?

Of course, we can't remove ClearDrawing from the API, or even change it's behavior, since that would break everyone's code.  I think we could update the documentation (since it currently does not state what happens with the layer) to indicate that the layer is not just cleared, but also removed from the map.

@pmeems , do you have any input regarding this?

**Comment by pmeems** [comment] 2018-09-18 06:22
I agree with @jerryfaust. We can't change the API but I will update the API documentation.

**Comment by pmeems** [comment] 2018-09-18 06:38
I've created https://mapwindow.atlassian.net/browse/DOC-14 and suggest to change the documentation to:

```
        /// <summary>
        /// Clears (removes) all the drawings on the drawing layer specified. And removes the layer handle.
        /// Call AxMap.NewDrawing again to create a new drawing layer to continue adding new elements.
        /// </summary>
        /// <param name="DrawHandle">Drawing handle of the drawing layer for which all drawings are to be cleared (removed).</param>
        public void ClearDrawing(int DrawHandle)
        {
            throw new NotImplementedException();
        }

        /// <summary>
        /// Clears (removes) all drawings on all drawing layers. And removes the layer handles.
        /// This method is slower than using ClearDrawing on a specific layer
        /// Call AxMap.NewDrawing again to create a new drawing layer to continue adding new elements.
        /// </summary>
        public void ClearDrawings()
        {
            throw new NotImplementedException();
        }

```

I'm not a native English speaker/writer. Is this improving the documentation? If not please post your suggestion.

**Comment by Nogginboink** [comment] 2018-09-19 17:08
Do you want to recommend in the docs that users use RemoveLayer instead and declare ClearDrawing deprecated? If the two calls do the same thing, I think this might be appropriate.

**Comment by jerryfaust** [comment] 2018-09-19 21:14
@Nogginboink 
I guess I didn't explain well-enough in my comment above.  The Drawing layers are managed separately from the Map layers, and the DrawHandles are not synonymous with LayerHandles.  As such, they are added/removed using NewDrawing and ClearDrawing, and they cannot be removed by calling RemoveLayer.

**Comment by jerryfaust** [comment] 2018-09-20 19:17
Paul (@pmeems)
I suggest only slight changes. something like the following:
```
/// <summary>
/// Clears all drawings on the specified drawing layer, and removes the drawing layer. The drawing handle will no longer be valid.
/// Call AxMap.NewDrawing again to create a new drawing layer to continue adding new elements.
/// </summary>
/// <param name="DrawHandle">Drawing handle of the drawing layer to be cleared (and removed).</param>
public void ClearDrawing(int DrawHandle)
{
	throw new NotImplementedException();
}

/// <summary>
/// Clears all drawings on all drawing layers, and removes all drawing layers.
/// This method is slower than using ClearDrawing on a specific layer.
/// Call AxMap.NewDrawing again to create a new drawing layer to continue adding new elements.
/// </summary>
public void ClearDrawings()
{
	throw new NotImplementedException();
}

```

**Comment by pmeems** [comment] 2018-09-21 07:58
I've updated the documentation:
https://www.mapwindow.org/documentation/mapwingis4.9/group__map__drawing__layers.html#ga730ec15a2690ec89187fc30b78d71139

Hopefully it is more clear now.

**Closed as completed by pmeems** 2018-09-21 07:58 UTC
Labels: enhancement
