### ISSUE TITLE
Setup does not create or remove mapwingis.ocx registry entries

### ISSUE THREAD

**Issue by Paul-Inf** [MapWindow/MapWinGIS#76] opened 2018-03-06 18:37 UTC
Hi,
I am trying to use MapWinGIS-only-v4.9.5.0-Win32.exe setup.
We are running into an issue where mapwingis.ocx registry entries are not being created\removed.
Tried registering\unregistering mapwingis.ocx manually via regsvr32 mapwingis.ocx & regsvr32 /u mapwingis.ocx with the same results - entries not created \ removed. 
Somehow first time around that I tried the control, registry entries got created but not after that.
I used ProcMon utility from SysInternals\Microsoft (https://live.sysinternals.com/procmon.exe) to monitor registry entries too - nothing is being created\removed there for mapwingis.ocx

Thanks

**Comment by jerryfaust** [comment] 2018-03-06 19:22
This may not apply in your case, but on some systems, I have had to run the installer and the regMapWinGIS.cmd "as Administrator" in order to update the registry.

**Comment by Paul-Inf** [comment] 2018-03-06 19:47
Thanks Jerry for your suggestion - re-tried it just right now running "as Administrator" - no effect. Registry entries are not being created. I took a look at MapWinGIS.ocx source code - MapWinGIS.cpp -> DllRegisterServer - it seems to be the standard code for registering COM components. By the looks of it something must be failing inside one of the following:
- _AtlModule.RegisterServer(TRUE)
or
-  AfxOleRegisterTypeLib(AfxGetInstanceHandle(), _tlid)
or
- COleObjectFactoryEx::UpdateRegistryAll(TRUE)
or
- _Module.RegisterServer(TRUE)

**Comment by jerryfaust** [comment] 2018-03-07 01:40
If you don't mind, please tell me a little about your environment;
What is the Windows version, and it is 32 or 64 bit?
Have you tried it on multiple machines, all with the same result?
Where are you looking to verify that the registry has not been written to (32/64 bit differences)?
Please don't take this is a bad way, but this installer/ocx has been in place for a little while now, and although it is not impossible that there is a problem with it, it is more likely that the issue is with the machine than with the ocx.

Respectfully,
Jerry.

**Comment by Paul-Inf** [comment] 2018-03-07 15:05
Hi Jerry,
I appreciate your responses, no worries - I am software developer myself.
I tried it on my Windows 10 64bit machine & my co-worker tried on his Windows 10 64bit machine - same result, registry entries not created \ removed.
My co-worker also tried it on Windows 8 64bit virtual machine and it worked - registry entries got created \ removed.
To verify that the entries are not created \ removed on my Windows 10 64bit machine I used 2 tools\approaches:
-	Regedit.exe - tried looking for the entries using Windows registry editing tool
-	ProcMon.exe (Process Monitor) - utility that allows one to monitor a process in terms of registry\file\network activity. 

Thanks

**Comment by pmeems** [comment] 2018-03-08 09:13
Just to jump in.
When you call `regsvr32 mapwingis.ocx` do you get a response? You should get a popup saying something like 'Registration was successful' or 'Couldn't register'. 
When you get the 'Couldn't register' message most likely some dependency is missing. You could use DependencyWalker to check, although this is a very old tool and it shows a lot of false-positives.
If you get the successful message you could have a look in Visual Studio if MapWinGIS is listed in the 'OCX' tab of the 'Add dependencies' form:
![image](https://user-images.githubusercontent.com/12067729/37142716-2f9c78aa-22b9-11e8-8106-c3e1dba7af4a.png)

**Comment by Paul-Inf** [comment] 2018-03-08 15:05
Thanks Paul,
To be more specific - there is no msg box popup at all - this is very strange, have not seen this happen at all in the past when working with registerable COM objects\controls. 
#1 Thank you for adding ‘help wanted’ tag  to my post, I  will try to tag my posts accordingly the next time
#2 There are no responses – the usual msg box you get saying that the COM ‘thing’ you were trying to register using regsvr32.exe registered properly does not show up, - this is another indication that something is not working as expected on Windows 10 machines..

**Comment by pmeems** [comment] 2018-03-08 15:24
No need to add tags. I will do it, then I know if I already replied/looked at the issue.

Indeed it is strange you don't get any response from `regsvr32`.
I run Win10 as well (Win10 Home x64) and I have no problems. Which version of Win10 are you running: Home, Professional, other.

Can you also try this possible solution I found online:
`cd \windows\syswow64`
`regsvr32 c:\filename.dll`

And did you check Visual Studio? MapWinGIS is not listed?

**Comment by Paul-Inf** [comment] 2018-03-09 16:55
I have Windows 10 Professional. 
My co-worker has discovered that the issue seems to do with adding a backslash "\" to the path.
Can you please modify the following 2 files in your setup to explicitly include '\" in the path:
regMapWinGIS.cmd
unregMapWinGIS.cmd
Thanks, much appreciated.

This is what I have tried manually & it worked for me:
Launch Admin console on Windows 10 Pro and go to c:\dev\MapWIinGIS
run
regsvr32.exe c:\dev\MapWinGIS\MapWinGIS.ocx
the above puts registry entries (confirmed by trying to look for MapWinGIS via regedit.exe)
regsvr32.exe /u c:\dev\MapWinGIS\MapWinGIS.ocx
the above removes registry entries (confirmed by trying to look for MapWinGIS via regedit.exe)
Please note that the full path is used - this seems to be crucial, based on my co-workers' comment - as long as there is a backslash "\" in the path it seems to make registration\unregistration work.

**Comment by pmeems** [comment] 2018-03-11 09:40
Thanks for finding a solution.
We currently use this in out bat-file:
```
@setlocal enableextensions
@cd /d "%~dp0"
rem The lines above are from http://www.codeproject.com/Tips/119828/Running-a-bat-file-as-administrator-Correcting-cur.aspx

REM Unregister any previous versions:
regsvr32 /u /s MapWinGIS.ocx
REM Register current version:
regsvr32 /s MapWinGIS.ocx
```

Where do you suggest we add a backslash? 
We cannot hard-code the working folder.

**Comment by Paul-Inf** [comment] 2018-03-12 14:45
This is what my co-worker suggested:
regsvr32 /s .\MapWinGIS.ocx
(.\ before MapWinGIS.ocx)

**Comment by anRoswell** [comment] 2018-06-22 19:36
Hola como les va, les cuento tengo el mismo error del compañeros al intentar utilizar el MapWinGis 4.9 con el visual studio 2012 profesional, en sistema operativo Windows 10 x64, ademas me sale un error 

++ Ya instale el Windows SDK, el .Net 4.5 y 4.7.
++ Ejecute el archivo regMapWinGIS.cmd

Realice la opción q dice Paul-Ing y nada

Si alguien a podido dar con la solución le agradezco lo comparta.

Error	1	Error en la tarea porque "AxImp.exe" no se encuentra o no está instalada la versión correcta de Microsoft Windows SDK. La tarea busca "AxImp.exe" en el subdirectorio "bin" de la ubicación especificada en el valor InstallationFolder de la clave del Registro HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Microsoft SDKs\Windows\v8.0A\WinSDK-NetFx40Tools-x86. Puede que el problema se solucione de una de estas formas:  1) Instale Microsoft Windows SDK. 2) Instale Visual Studio 2010. 3) Establezca manualmente la clave del Registro indicada en la ubicación correcta. 4) Pase la ubicación correcta en el parámetro "ToolPath" de la tarea.	ShapeFile - MapWinGis

Advertencia	2	No se pudo encontrar el componente 'MapWinGIS' al que se hace referencia. 	ShapeFile - MapWinGis

**Comment by simran-sidd** [comment] 2018-10-01 07:13
If you try to download the [missing ocx file](https://unfitpc.com/mapwingis-ocx) in your operating system and have the no idea to how to correct it without facing the complication it is very easy method to complete the registration process

**Comment by pmeems** [comment] 2019-03-28 15:52
I'm closing this issue.
If needed you can repost at our [MapWinGIS forum](https://mapwindow.discourse.group/c/mapwingis)

**Closed as completed by pmeems** 2019-03-28 15:52 UTC
Labels: help wanted
