### ISSUE TITLE
Russian language does not work in OgrDatasource

### ISSUE THREAD

**Issue by Waleryth** [MapWindow/MapWinGIS#121] opened 2018-10-03 10:21 UTC
Hello! I am working on my project based on Mapwingis.osx.
If I download the Shapefile `shpfile.Open("shape.shp", null);` then the labels are signed correctly.
But if I upload the file as follows

![image](https://user-images.githubusercontent.com/30282010/46405059-d28ee700-c728-11e8-9a25-0e669eb41556.png)

then the labels are not signed correctly.
What should I do?

![2018-10-03_161607](https://user-images.githubusercontent.com/30282010/46404789-0c132280-c728-11e8-9920-28694882be71.jpg)
![2018-10-03_161631](https://user-images.githubusercontent.com/30282010/46404790-0c132280-c728-11e8-8e92-5bbb41fca3ba.jpg)

**Comment by Waleryth** [comment] 2018-10-03 10:26
Sampe programm
[TestMapLabeling.zip](https://github.com/MapWindow/MapWinGIS/files/2441595/TestMapLabeling.zip)

Sample Shapefile
[ShapeFile.zip](https://github.com/MapWindow/MapWinGIS/files/2441597/ShapeFile.zip)

**Comment by Waleryth** [comment] 2018-10-03 10:31
In Mapwindow 5, the Russian language also does not work if you connect a layer from the server.

![image](https://user-images.githubusercontent.com/30282010/46405300-a3c54080-c729-11e8-8394-ec6a54a250c6.png)

**Comment by Waleryth** [comment] 2018-10-03 11:55
This code also does not make it possible to properly label the tags.
`
            axMap1.Clear();
            string query = "Select * from monitoring_object";
            int layerHandle = axMap1.AddLayerFromDatabase("Maps\\monitoring_object.shp", query, true);
            MapWinGIS.Shapefile shpfile = new MapWinGIS.Shapefile();
            shpfile = axMap1.get_Shapefile(layerHandle);
            shpfile.Labels.Generate("[Type]", tkLabelPositioning.lpCenter, false);
            shpfile.Labels.FrameVisible = true;
            shpfile.Labels.FrameType = tkLabelFrameType.lfRectangle;
`

**Comment by jerryfaust** [comment] 2018-10-23 06:02
Related to Atlassian MWGIS-112, an update has been submitted to the 'develop' branch to properly convert GDAL-based UTF-8 encoded strings to their proper format.  Changes were also made that relate to internal Shapefiles, based on their associated code pages.

**Comment by jerryfaust** [comment] 2018-11-15 18:07
Closing this issue since I believe it is resolved.  We can re-open if it is determined not to be resolved.

**Closed as completed by jerryfaust** 2018-11-15 18:07 UTC

**Comment by pmeems** [comment] 2018-11-28 16:29
I can confirm this is solved in the current dev-version.
I created a unit test for this:
```
[TestMethod]
public void ReadRussianDataFromOgrDatasource()
{
    // https://github.com/MapWindow/MapWinGIS/issues/121
    _axMap1 = Helper.GetAxMap();
    _axMap1.Clear(); 
    _axMap1.TileProvider = tkTileProvider.None;
    _axMap1.ZoomBehavior = tkZoomBehavior.zbDefault;
    _axMap1.KnownExtents = tkKnownExtents.keWorld;

    var sfName = @"Issues\MWGIS-72\monitoring_object.shp";
    var baseName = Path.GetFileNameWithoutExtension(sfName);
    var query = "Select * from monitoring_object";
    var layerHandle = _axMap1.AddLayerFromDatabase(sfName, query, true);
    var shpfile = _axMap1.get_Shapefile(layerHandle); 
    shpfile.Labels.Generate("[Type]", tkLabelPositioning.lpCenter, false); 
    shpfile.Labels.FrameVisible = true; 
    shpfile.Labels.FrameType = tkLabelFrameType.lfRectangle;
    Helper.SaveSnapshot(_axMap1, $"{baseName}.jpg", _axMap1.get_layerExtents(layerHandle));
}
```

The resulting snapshot:
![monitoring_object](https://user-images.githubusercontent.com/12067729/49166228-343b8e00-f333-11e8-8aea-18c15de8ecf5.jpg)
