### ISSUE TITLE
SQLite UTF-8 Chinese Label Error

### ISSUE THREAD

**Issue by wanghanbo** [MapWindow/MapWinGIS#68] opened 2018-02-02 06:09 UTC
Hello! Sorry for my English.
I'm trying to create labels on the map from my SQLite database, but it turned out that the encoding of the Russian language is not supported.
I Checked the SQLIte database. The field "FileName" in Tmpcadd table has chinese character and saved by unicode. But when I use [MapWindow5] to load and Label the field, the label text error occured like following image。  

Using SQLite Expert to view TmpCadd(encoding is utf-8),FileName field is correct.
![image](https://user-images.githubusercontent.com/5698893/35719000-0448ad74-0822-11e8-8efe-d80e0d0b023e.png)
So I run MapWindow 5 to load TmpCadd and labeling it by FileName field, chinese charater is error:
![image](https://user-images.githubusercontent.com/5698893/35719033-30dd63b6-0822-11e8-9089-d777ff27b9af.png)
I checked [filename] field and found labeling text is as same as SQLite expert's error when encoding is ANSI as following.
![image](https://user-images.githubusercontent.com/5698893/35719077-77c14a68-0822-11e8-9803-a9b9ebbb51d9.png)
![image](https://user-images.githubusercontent.com/5698893/35719082-826de390-0822-11e8-9062-fcee9e513c92.png)
What can I do?
[tempdb.zip](https://github.com/MapWindow/MapWinGIS/files/1688245/tempdb.zip) @pmeems

**Comment by pmeems** [comment] 2018-02-02 07:50
Currently MapWinGIS does not fully support UNICODE.
It is on the top of our list, but it is a huge change.

Thanks for the test files. I created https://mapwindow.atlassian.net/browse/MWGIS-109 for this.

One thing you could try is to convert the SQLite file to shapefile. Perhaps the labels will work, but I'm not sure. You can use GdalVectorTranslate for this: http://www.mapwindow.org/documentation/mapwingis4.9/class_gdal_utils.html#adfeb0f1ebfcd629a5c8b05a2dfada8d9

If you are a C++ developer you can also try to fix it yourself and provide a patch.

**Comment by jerryfaust** [comment] 2018-10-24 05:06
This issue is now fixed, based on the same changes submitted for Atlassian MWGIS-112.  Characters from GDAL datasource had to be converted from UTF-8.

**Comment by pmeems** [comment] 2018-11-28 16:48
I can confirm this is now fixed.
A screenshot using the provided SQLite sample data opened in MW5:
![image](https://user-images.githubusercontent.com/12067729/49167495-c5abff80-f335-11e8-9003-92b37a9fb7e5.png)

**Closed as completed** 2018-11-28 16:48 UTC
Labels: enhancement

**Comment by ZiYou2333** [comment] 2019-07-23 01:54
Who can help me,"var cellvalues = sf.get_CellValue(i, shpIndex).ToString();" get the corresponding value in the table through this code, Chinese cannot be displayed properly, what is the reason for this?thank you @pmeems
